#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

#
# This cloud config part is installed on all hosts. It includes
# ssh users and Docker as a running service.
users:
  - name: torsten
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGY2GZU19neGfVAVuIOKt0iIMKUDDz0H72dPROsVPFen

packages:
  - docker
  - jq
  - nc

runcmd:
  - amazon-linux-extras install epel -y
  - systemctl daemon-reload

  - echo "{\"dns\":[\"$(grep nameserver /etc/resolv.conf | awk -d'' '{print $2}')\", \"8.8.8.8\"]}" > /etc/docker/daemon.json
  - systemctl enable docker
  - systemctl start docker