#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

write_files:
  - content: |
      [Unit]
      Description=Zookeeper
      Requires=docker.service
      After=docker.service

      [Service]
      EnvironmentFile=/etc/default/zookeeper
      Restart=always
      ExecStartPre=-/usr/bin/docker stop %n
      ExecStartPre=-/usr/bin/docker rm %n
      ExecStartPre=/usr/bin/docker pull zookeeper:3.5
      ExecStart=/usr/bin/docker run --rm --name %n \
        -p 2181:2181 -p 2888:2888 -p 3888:3888 \
        -e ZOO_4LW_COMMANDS_WHITELIST=srvr,ruok \
        -e ZOO_MY_ID=${ZOO_MY_ID} \
        -e ZOO_SERVERS=${ZOO_SERVERS} \
        zookeeper:3.5

      [Install]
      WantedBy=local.target
    path: /etc/systemd/system/zookeeper.service
  - content: |
      #!/bin/bash
      ZOO_HOST_IP=$(curl -s curl http://169.254.169.254/latest/meta-data/local-ipv4)
      ZOO_INSTANCE_IPS=$(aws ec2 describe-instances --region eu-west-1 --instance-ids \
        $(aws autoscaling describe-auto-scaling-instances --region eu-west-1 --output text \
            --query "AutoScalingInstances[?AutoScalingGroupName=='zookeeper'].InstanceId") \
      --query "Reservations[].Instances[].PrivateIpAddress" | jq -r '.[]')
      ZOO_ALL_SERVERS=$(echo "$ZOO_INSTANCE_IPS" | sed -E 's/^([0-9]+\.[0-9]+\.[0-9]+\.([0-9]+))$/server.\2=\1:2888:3888;2181/' | sort | paste -sd ' ')
      ZOO_SERVERS=$(echo ${ZOO_ALL_SERVERS} |sed -e "s/${ZOO_HOST_IP}/0.0.0.0/")
      ZOO_MY_ID=$(echo $ZOO_HOST_IP | sed -E 's/^[0-9]+\.[0-9]+\.[0-9]+\.([0-9]+)$/\1/')

      # write zookeeper env
      echo "ZOO_SERVERS=${ZOO_SERVERS}"
      echo "ZOO_MY_ID=${ZOO_MY_ID}"
      echo "ZOO_HOST_IP=${ZOO_HOST_IP}"
    path: /opt/zookeeper-env.sh
    permissions: '0755'

runcmd:
  - /opt/zookeeper-env.sh > /etc/default/zookeeper
  - systemctl enable zookeeper
  - systemctl start zookeeper
